/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ro.ugal.aciee.boxa;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        Boxa[] boxe = new Boxa[10];
        for (int i = 0; i < 10; i++) {
            boxe[i] = new Boxa(i % 2 == 0, i % 3 == 0, (i + 1) * 1000 + "", (i + 1) * 10 + "", (i + 1) + "", "Marca " + i, true, "1 an " + i, "Culoare " + i, i*0.5);
            //RezistentApa, RezistentPraf, CapacitateAcumulator, DistenataOperare, TimpIncarcare, Marca, Garantie, TermenGarantie, Culoare, Greutate
        }
        
        DefaultTableModel model = (DefaultTableModel)TabelBoxa.getModel();
        for(Boxa i : boxe){ 
            model.addRow(new Object[]{
                i.Marca,
                i.Culoare,
                i.RezistentApa(),
                i.RezistentPraf(),
                Integer.parseInt(i.CapacitateAcumulator()),
                Integer.parseInt(i.DistantaOperare()),
                Integer.parseInt(i.TimpIncarcare())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RezistentPraf = new javax.swing.JCheckBox();
        RezistentApa = new javax.swing.JCheckBox();
        CapacitateAcumulator = new javax.swing.JTextField();
        DistantaOperare = new javax.swing.JTextField();
        TimpIncarcare = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Garantie = new javax.swing.JCheckBox();
        TermenGarantie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Culoare = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBoxa = new javax.swing.JTable();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        SelectieFiltrare = new javax.swing.JComboBox<>();
        Minim = new javax.swing.JTextField();
        Maxim = new javax.swing.JTextField();
        Filtrare = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Open = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RezistentPraf.setText("Rezistent Praf");
        RezistentPraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RezistentPrafActionPerformed(evt);
            }
        });

        RezistentApa.setText("Rezistent Apa");
        RezistentApa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RezistentApaActionPerformed(evt);
            }
        });

        CapacitateAcumulator.setText("4200");

        DistantaOperare.setText("5");
        DistantaOperare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistantaOperareActionPerformed(evt);
            }
        });

        TimpIncarcare.setText("3");

        jLabel1.setText("Capacitate Acumulator");

        jLabel2.setText("Distanta Operare");

        jLabel3.setText("Timp Incarcare");

        Garantie.setText("Garantie");
        Garantie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GarantieActionPerformed(evt);
            }
        });

        TermenGarantie.setText("2");

        jLabel4.setText("Termen Garantie");

        Marca.setText("JBL");

        jLabel5.setText("Marca");

        Culoare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negru", "Alb", "Gri", "Roz" }));

        jLabel6.setText("Culoare");

        jLabel7.setText("Boxa");

        TabelBoxa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Culoare", "Rezistent Apa", "Rezistent Praf", "Capacitate Acumulator", "Distanta Operare", "Timp Incarcare"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelBoxa);

        Add.setText("Add\n");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        SelectieFiltrare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Capacitate Acumulator", "Distanta Operare", "Timp Incarcare" }));

        Minim.setText("Minim");

        Maxim.setText("Maxim");

        Filtrare.setText("Filtrare");
        Filtrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrareActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RezistentPraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RezistentApa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CapacitateAcumulator, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DistantaOperare, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TimpIncarcare, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(Garantie, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TermenGarantie, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Culoare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Minim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Maxim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(SelectieFiltrare, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Filtrare))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Open))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add)
                            .addComponent(Delete)
                            .addComponent(Save)
                            .addComponent(Open)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RezistentPraf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RezistentApa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CapacitateAcumulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DistantaOperare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TimpIncarcare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Garantie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TermenGarantie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Culoare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectieFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Minim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Maxim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Filtrare)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RezistentPrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RezistentPrafActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RezistentPrafActionPerformed

    private void RezistentApaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RezistentApaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RezistentApaActionPerformed

    private void DistantaOperareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistantaOperareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistantaOperareActionPerformed

    private void GarantieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GarantieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GarantieActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TabelBoxa.getModel();
        
        boolean areGarantie = Garantie.isSelected();
        boolean esteRezistentPraf = RezistentPraf.isSelected();
        boolean esteRezistentApa = RezistentApa.isSelected();
        int capacitateaDeIncarcare = Integer.parseInt(CapacitateAcumulator.getText());
        int distantaDeOperare = Integer.parseInt( DistantaOperare.getText());
        int timpulDeIncarcare = Integer.parseInt(TimpIncarcare.getText());
        String termenulGarantiei = TermenGarantie.getText();
        String marca = Marca.getText();
        String culoare = (String) Culoare.getSelectedItem();
        
        model.addRow(new Object[]{
  marca, 
  culoare, 
  esteRezistentApa, 
  esteRezistentPraf, 
  capacitateaDeIncarcare, 
  distantaDeOperare, 
  timpulDeIncarcare
});
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TabelBoxa.getModel();
model.removeRow(TabelBoxa.getSelectedRow());
    }//GEN-LAST:event_DeleteActionPerformed

    private void FiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrareActionPerformed
        // TODO add your handling code here:
        int minim = Integer.parseInt(Minim.getText());
        int maxim = Integer.parseInt(Maxim.getText());
        int selectieFiltrare = SelectieFiltrare.getSelectedIndex()+4;
        
        DefaultTableModel model = (DefaultTableModel)TabelBoxa.getModel();
        for(int i = model.getRowCount() - 1; i >=0; i--){
            int valoare = (int) model.getValueAt(i, selectieFiltrare);
            
            System.out.println(valoare);
            
            if(minim > valoare || maxim < valoare){
                model.removeRow(i);
            }
        }
        
    }//GEN-LAST:event_FiltrareActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TabelBoxa.getModel();
        JFileChooser fileChooser = new JFileChooser(); //window alegere fisier
        fileChooser.showSaveDialog(this);//show
           
        String chosenFileName = fileChooser.getSelectedFile().getPath();
        
        try {
            FileWriter writer = new FileWriter(chosenFileName); //scriere
            writer.write("Marca,Culoare,Rezistet Apa,Rezistent Praf,Capacitate Acumulator,Distanta Operare,Timp Incarcare");//header
            for(int i = 0; i < model.getRowCount(); i++) {
                System.out.println(i);
                writer.write(TabelBoxa.getValueAt(i, 0) + "," +
                                TabelBoxa.getValueAt(i, 1) + "," +
                                TabelBoxa.getValueAt(i, 2) + "," +
                                TabelBoxa.getValueAt(i, 3) + "," +
                                TabelBoxa.getValueAt(i, 4) + "," +
                                TabelBoxa.getValueAt(i, 5) + "," +
                                TabelBoxa.getValueAt(i, 6) + "\n"); //linie noua //Valori din tabel > fisier
            }
            writer.close();
        } catch (IOException e) {
            System.out.println("Failed to write to file."); //eroare
            e.printStackTrace();
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TabelBoxa.getModel();
        model.setRowCount(0);

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
           
        try {
            BufferedReader reader = new BufferedReader(new FileReader(fileChooser.getSelectedFile().getPath()));//citire
            //read line by line
            reader.readLine(); // CSV Header
            String currentLine = reader.readLine();
            while(currentLine != null) {
                String[] atribute = currentLine.split(","); //imparte linia la ","
                model.addRow(new Object[]{
                    atribute[0],
                    atribute[1],
                    Boolean.parseBoolean(atribute[2]),
                    Boolean.parseBoolean(atribute[3]),
                    Integer.parseInt(atribute[4]),
                    Integer.parseInt(atribute[5]),
                    Integer.parseInt(atribute[6]) 
                });
                currentLine = reader.readLine();
            } 
        }catch (IOException e){
            e.printStackTrace();//eroare
        }
    }//GEN-LAST:event_OpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField CapacitateAcumulator;
    private javax.swing.JComboBox<String> Culoare;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField DistantaOperare;
    private javax.swing.JButton Filtrare;
    private javax.swing.JCheckBox Garantie;
    private javax.swing.JTextField Marca;
    private javax.swing.JTextField Maxim;
    private javax.swing.JTextField Minim;
    private javax.swing.JButton Open;
    private javax.swing.JCheckBox RezistentApa;
    private javax.swing.JCheckBox RezistentPraf;
    private javax.swing.JButton Save;
    private javax.swing.JComboBox<String> SelectieFiltrare;
    private javax.swing.JTable TabelBoxa;
    private javax.swing.JTextField TermenGarantie;
    private javax.swing.JTextField TimpIncarcare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
